# Generated by Django 3.2.4 on 2021-06-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
    ]
